services:

  backend:
    build: .
    container_name: wnet_backend
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      POSTGRES_HOST: database
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres
    container_name: wnet_database
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wnetdb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      timeout: 10s
      retries: 5